name: Daily dbt Cloud Integration Tests

on:
  schedule:
    - cron: '45 2 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  daily-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@19bb51245e9c80abacb2e91cc42b33fa478b8639 # actions/setup-go@v4
        with:
          go-version: '>=1.17.0'

      - name: Install dependencies
        run: make setup

      - name: Install Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # hashicorp/setup-terraform@v3

      - name: Run unit tests
        run: make test

      - name: Run acceptance tests
        run: make test-acceptance
        env:
          DBT_CLOUD_ACCOUNT_ID: ${{ secrets.TEST_DBT_CLOUD_ACCOUNT_ID }}
          DBT_CLOUD_TOKEN: ${{ secrets.TEST_DBT_CLOUD_TOKEN }}
          DBT_CLOUD_HOST_URL: ${{ secrets.TEST_DBT_CLOUD_HOST_URL }}
          DBT_ACCEPTANCE_TEST_LINEAGE_INTEGRATION: ${{ secrets.DBT_ACCEPTANCE_TEST_LINEAGE_INTEGRATION }}
          # Platform metadata credential tests
          ACC_TEST_SNOWFLAKE_ACCOUNT: ${{ secrets.ACC_TEST_SNOWFLAKE_ACCOUNT }}
          ACC_TEST_SNOWFLAKE_DATABASE: ${{ secrets.ACC_TEST_SNOWFLAKE_DATABASE }}
          ACC_TEST_SNOWFLAKE_WAREHOUSE: ${{ secrets.ACC_TEST_SNOWFLAKE_WAREHOUSE }}
          ACC_TEST_SNOWFLAKE_USER: ${{ secrets.ACC_TEST_SNOWFLAKE_USER }}
          ACC_TEST_SNOWFLAKE_PASSWORD: ${{ secrets.ACC_TEST_SNOWFLAKE_PASSWORD }}
          ACC_TEST_SNOWFLAKE_ROLE: ${{ secrets.ACC_TEST_SNOWFLAKE_ROLE }}
